<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['uri_segment']       = 3;
$config['num_links']         = 5;
$config['full_tag_open']     = '<ul class="pagination">';
$config['full_tag_close']    = '</ul>';
$config['first_link']        = '<i class="fa fa-fast-backward"></i>';
$config['first_tag_open']    = '<li>';
$config['first_tag_close']   = '</li>';
$config['last_link']         = '<i class="fa fa-fast-forward"></i>';
$config['last_tag_open']     = '<li>';
$config['last_tag_close']    = '</li>';
$config['next_link']         = '<i class="fa fa-step-forward"></i>';
$config['next_tag_open']     = '<li>';
$config['next_tag_close']    = '</li>';
$config['prev_link']         = '<i class="fa fa-step-backward"></i>';
$config['prev_tag_open']     = '<li>';
$config['prev_tag_close']    = '</li>';
$config['cur_tag_open']      = '<li class="active"><a href="#">';
$config['cur_tag_close']     = '</a></li>';
$config['num_tag_open']      = '<li>';
$config['num_tag_close']     = '</li>';
$config['page_query_string'] = FALSE;
